### PR TITLE
Added protection against TileEntity casting exceptions

### PR DESCRIPTION
**Pull request by seph86**
Shout out to the tab spaces lol.

I only did a small amount of testing in the dev environment but it does indeed stop crashing out from the railcraft tiles.  But of course just verify I haven't unknowingly broken something before adding it to the main repository just in case.

Seph

### CODE REVIEW

**Comment by CelesTek-Team** [comment]
This looks good, but wouldn't it be easier to get the tile entity and do an instanceof check to make sure if it is TileEnergyPylon before casting? That would make sure that it is nether null, or some other TileEntity. It would also make it a bit cleaner instead of using a try-catch.

**Comment by seph86** [comment]
Good call.  Completely forgot that was a thing.

I am curious though why that wasn't implemented in the first place?  Lots of people reporting the cast exception before I did this dirty hack.

**Comment by CelesTek-Team** [comment]
We will be completely honest: this is our first mod ever, and we were not exactly sure why was it happening at all. Something like this was planned for the next release anyway though, as even the Iron Chests mod is causing a similar crash.

**Comment by seph86** [comment]
Fair enough.

For a first ever mod, it's a damn good one.

**Comment by seph86** [comment]
Much cleaner with instanceof, feel free to pull or close this request.  

Happy coding.

**Pull request merged**
